site_name: CDS Hooks

theme:
  name: 'material'
  logo: 'images/logo-square.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'grey'
    accent: 'red'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/cds-hooks'

nav:
- Home: 'index.md'
- Releases:
  - 1.0: '1.0/index.md'
- Hooks:
  - 'patient-view 4' : 'hooks/patient-view/2020Feb/patient-view.md'
- Archived Ballots:
  - Home: 'ballots/index.md'
  - 2018May: 'ballots/2018May/index.html'

repo_url: 'https://github.com/hl7/cds-hooks-hl7-site'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true

copyright: © 2019 HL7 & Boston Children's Hospital.<p></p> <img alt="HL7 International" src="/images/hl7-logo.png" /><p></p><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
