site_name: CDS Hooks

theme:
  name: 'material'
  logo: 'images/logo-square.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'grey'
    accent: 'red'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/cds-hooks'

nav:
- Home: 'index.md'
- Releases:
  - 1.0: '1.0/index.md'
  - 2.0: '2.0/index.md'
- Hooks:
  - 'patient_view 5':
    - 'patient-view (STU1 release)' : 'hooks/patient-view/STU1/patient-view.md'
    - 'patient-view (STU1 ballot)' : 'hooks/patient-view/2020Feb/patient-view.md'
    - 'patient-view (current build)' : 'https://cds-hooks.org/hooks/patient-view/'
  - 'order-sign 5' : 
    - 'order-sign (STU1 release)' : 'hooks/order-sign/STU1/order-sign.md'
    - 'order-sign (STU1 ballot)' : 'hooks/order-sign/2023SepSTU1Ballot/order-sign.md'
    - 'order-sign (current build)' : 'https://cds-hooks.org/hooks/order-sign/'
  - 'order-select 4' : 
    - 'order-select (STU1 release)' : 'hooks/order-select/STU1/order-select.md'
    - 'order-select (STU1 ballot)' : 'hooks/order-select/2023SepSTU1Ballot/order-select.md'
    - 'order-select (current build)' : 'https://cds-hooks.org/hooks/order-select/'
  - 'order-dispatch 1' : 
    - 'order-dispatch (STU1 release)' : 'hooks/order-dispatch/STU1/order-dispatch.md'
    - 'order-dispatch (STU1 ballot)' : 'hooks/order-dispatch/2023SepSTU1Ballot/order-dispatch.md'
    - 'order-dispatch (current build)' : 'https://cds-hooks.org/hooks/order-dispatch/'
  - 'encounter-start 1' : 
    - 'encounter-start (STU1 release)' : 'hooks/encounter-start/STU1/encounter-start.md'
    - 'encounter-start (STU1 ballot)' : 'hooks/encounter-start/2023SepSTU1Ballot/encounter-start.md'
    - 'encounter-start (current build)' : 'https://cds-hooks.org/hooks/encounter-start/'
  - 'encounter-discharge 1' : 
    - 'encounter-discharge (STU1 release)' : 'hooks/encounter-discharge/STU1/encounter-discharge.md'
    - 'encounter-discharge (STU1 ballot)' : 'hooks/encounter-discharge/2023SepSTU1Ballot/encounter-discharge.md'
    - 'encounter-discharge (current build)' : 'https://cds-hooks.org/hooks/encounter-discharge/'
  - 'appointment-book 1' :
    - 'appointment-book (STU1 release)' : 'hooks/appointment-book/STU1/appointment-book.md'
    - 'appointment-book (STU1 ballot)' : 'hooks/appointment-book/2023SepSTU1Ballot/appointment-book.md'
    - 'appointment-book (current build)' : 'https://cds-hooks.org/hooks/appointment-book/'
- Ballots:
  - Home: 'ballots/index.md'
  - 2018May: 'ballots/2018May/index.html'
  - 2020Sep: 'ballots/2020Sep/index.md'
  - 2023Sep: 'ballots/2023Sep/index.md'

repo_url: 'https://github.com/hl7/cds-hooks-hl7-site'
edit_uri: ''

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true

copyright: © 2019 HL7 & Boston Children's Hospital.<p></p> <img alt="HL7 International" src="/images/hl7-logo.png" /><p></p><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
